# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
workspace 'SheQuanMC'
inhibit_all_warnings!

target 'SheQuanMC' do
  # Comment the next line if you don't want to use dynamic frameworks
  
use_frameworks!
  # Pods for SheQuanMC

pod 'LDStreaming', :path => "LDStreaming"
pod 'LDMessage', :path => "LDMessage"
pod 'CocoaAsyncSocket', :path => "CocoaAsyncSocket"
pod 'CocoaLumberjack', :path => "CocoaLumberjack"
pod 'Protobuf', :path => "protobuf"
pod 'FaceVer', :path => "FaceVer"
pod 'SnapKit'

pod 'DZNEmptyDataSet'
pod 'JFPopup'
pod 'HXPhotoPicker'
pod 'MJRefresh', '~> 3.7.5'
pod 'IQKeyboardManager'
pod 'Moya'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'HandyJSON', '~> 5.0.2'
pod 'SDWebImage'
pod 'JXPhotoBrowser'
pod 'TZImagePickerController'
end


target 'App' do
  use_frameworks!
project 'App/App'
pod 'LDStreaming', :path => "LDStreaming"
pod 'LDStreaming', :path => "LDStreaming"
pod 'LDMessage', :path => "LDMessage"
pod 'CocoaAsyncSocket', :path => "CocoaAsyncSocket"
pod 'CocoaLumberjack', :path => "CocoaLumberjack"
pod 'Protobuf', :path => "protobuf"
pod 'FaceVer', :path => "FaceVer"
pod 'SnapKit'

pod 'DZNEmptyDataSet'
pod 'JFPopup'
pod 'HXPhotoPicker'
pod 'MJRefresh', '~> 3.7.5'
pod 'IQKeyboardManager'
pod 'Moya'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'HandyJSON', '~> 5.0.2'
pod 'SDWebImage'
pod 'JXPhotoBrowser'
pod 'TZImagePickerController'
end


target 'Util' do
  use_frameworks!
pod 'LDStreaming', :path => "LDStreaming"
pod 'LDStreaming', :path => "LDStreaming"
pod 'LDMessage', :path => "LDMessage"
pod 'CocoaAsyncSocket', :path => "CocoaAsyncSocket"
pod 'CocoaLumberjack', :path => "CocoaLumberjack"
pod 'Protobuf', :path => "protobuf"
pod 'FaceVer', :path => "FaceVer"
project 'Util/Util'
pod 'SnapKit'

pod 'DZNEmptyDataSet'
pod 'JFPopup'
pod 'HXPhotoPicker'
pod 'MJRefresh', '~> 3.7.5'
pod 'IQKeyboardManager'
pod 'Moya'
pod 'SwiftyJSON'
pod 'RealmSwift'
pod 'HandyJSON', '~> 5.0.2'
pod 'SDWebImage'
pod 'JXPhotoBrowser'
pod 'TZImagePickerController'
end

